export let players = [
  {
    player_id: 1,
    first_name: "Alina",
    last_name: "De Benedetti",
    age: 21,
    height: 155.1,
    position: "middle blocker",
    team_name: "Team A",
    country: "Vietnam",
    jersey_number: 33,
    experience_years: 0,
  },
  {
    player_id: 2,
    first_name: "Tobe",
    last_name: "Swadlinge",
    age: 28,
    height: 184.2,
    position: "libero",
    team_name: "Team A",
    country: "Brazil",
    jersey_number: 53,
    experience_years: 1,
  },
  {
    player_id: 3,
    first_name: "Walther",
    last_name: "Densun",
    age: 33,
    height: 163.4,
    position: "middle blocker",
    team_name: "Team B",
    country: "China",
    jersey_number: 89,
    experience_years: 15,
  },
  {
    player_id: 4,
    first_name: "Justin",
    last_name: "Sproul",
    age: 34,
    height: 153.0,
    position: "opposite hitter",
    team_name: "Team B",
    country: "China",
    jersey_number: 24,
    experience_years: 3,
  },
  {
    player_id: 5,
    first_name: "Neila",
    last_name: "Merioth",
    age: 30,
    height: 186.0,
    position: "libero",
    team_name: "Team B",
    country: "Indonesia",
    jersey_number: 29,
    experience_years: 3,
  },
  {
    player_id: 6,
    first_name: "Harley",
    last_name: "Arundale",
    age: 24,
    height: 182.6,
    position: "middle blocker",
    team_name: "Team C",
    country: "China",
    jersey_number: 43,
    experience_years: 9,
  },
  {
    player_id: 7,
    first_name: "Tades",
    last_name: "Chung",
    age: 31,
    height: 190.6,
    position: "opposite hitter",
    team_name: "Team C",
    country: "Philippines",
    jersey_number: 10,
    experience_years: 9,
  },
  {
    player_id: 8,
    first_name: "Elliott",
    last_name: "Cuniffe",
    age: 33,
    height: 153.7,
    position: "opposite hitter",
    team_name: "Team A",
    country: "China",
    jersey_number: 86,
    experience_years: 7,
  },
  {
    player_id: 9,
    first_name: "Son",
    last_name: "Pleven",
    age: 37,
    height: 162.2,
    position: "middle blocker",
    team_name: "Team C",
    country: "Mexico",
    jersey_number: 48,
    experience_years: 16,
  },
  {
    player_id: 10,
    first_name: "Constantine",
    last_name: "Flight",
    age: 26,
    height: 171.7,
    position: "libero",
    team_name: "Team A",
    country: "Ireland",
    jersey_number: 56,
    experience_years: 4,
  },
  {
    player_id: 11,
    first_name: "Adrianne",
    last_name: "Ewbach",
    age: 25,
    height: 167.8,
    position: "opposite hitter",
    team_name: "Team B",
    country: "Philippines",
    jersey_number: 96,
    experience_years: 0,
  },
  {
    player_id: 12,
    first_name: "Nell",
    last_name: "Wellbelove",
    age: 23,
    height: 194.5,
    position: "outside hitter",
    team_name: "Team C",
    country: "Mongolia",
    jersey_number: 31,
    experience_years: 0,
  },
  {
    player_id: 13,
    first_name: "Ingaborg",
    last_name: "Ayto",
    age: 34,
    height: 179.3,
    position: "outside hitter",
    team_name: "Team B",
    country: "Tunisia",
    jersey_number: 13,
    experience_years: 5,
  },
  {
    player_id: 14,
    first_name: "Bailie",
    last_name: "Joire",
    age: 28,
    height: 171.5,
    position: "setter",
    team_name: "Team C",
    country: "Myanmar",
    jersey_number: 10,
    experience_years: 13,
  },
  {
    player_id: 15,
    first_name: "Godart",
    last_name: "Archbell",
    age: 26,
    height: 157.5,
    position: "opposite hitter",
    team_name: "Team B",
    country: "Armenia",
    jersey_number: 75,
    experience_years: 14,
  },
  {
    player_id: 16,
    first_name: "Stephannie",
    last_name: "Pays",
    age: 34,
    height: 197.6,
    position: "middle blocker",
    team_name: "Team A",
    country: "Guatemala",
    jersey_number: 50,
    experience_years: 20,
  },
  {
    player_id: 17,
    first_name: "Rebekah",
    last_name: "Parfitt",
    age: 28,
    height: 199.4,
    position: "setter",
    team_name: "Team A",
    country: "Brazil",
    jersey_number: 9,
    experience_years: 14,
  },
  {
    player_id: 18,
    first_name: "Jeffy",
    last_name: "Eakeley",
    age: 40,
    height: 151.8,
    position: "setter",
    team_name: "Team B",
    country: "China",
    jersey_number: 7,
    experience_years: 15,
  },
  {
    player_id: 19,
    first_name: "Eloisa",
    last_name: "Crinson",
    age: 37,
    height: 161.7,
    position: "setter",
    team_name: "Team B",
    country: "China",
    jersey_number: 61,
    experience_years: 8,
  },
  {
    player_id: 20,
    first_name: "Aida",
    last_name: "Cyphus",
    age: 22,
    height: 155.0,
    position: "libero",
    team_name: "Team C",
    country: "Indonesia",
    jersey_number: 25,
    experience_years: 2,
  },
  {
    player_id: 21,
    first_name: "Archy",
    last_name: "Rosenblath",
    age: 26,
    height: 196.9,
    position: "middle blocker",
    team_name: "Team B",
    country: "China",
    jersey_number: 30,
    experience_years: 17,
  },
  {
    player_id: 22,
    first_name: "Dorry",
    last_name: "Woolfall",
    age: 20,
    height: 182.1,
    position: "setter",
    team_name: "Team C",
    country: "France",
    jersey_number: 68,
    experience_years: 4,
  },
  {
    player_id: 23,
    first_name: "Ingaborg",
    last_name: "Stronghill",
    age: 37,
    height: 166.0,
    position: "outside hitter",
    team_name: "Team A",
    country: "China",
    jersey_number: 81,
    experience_years: 5,
  },
  {
    player_id: 24,
    first_name: "Giusto",
    last_name: "Kairns",
    age: 33,
    height: 192.8,
    position: "outside hitter",
    team_name: "Team A",
    country: "China",
    jersey_number: 23,
    experience_years: 11,
  },
  {
    player_id: 25,
    first_name: "Ruddy",
    last_name: "Pevreal",
    age: 31,
    height: 160.4,
    position: "setter",
    team_name: "Team C",
    country: "Sweden",
    jersey_number: 53,
    experience_years: 3,
  },
  {
    player_id: 26,
    first_name: "Danielle",
    last_name: "Castelli",
    age: 40,
    height: 195.5,
    position: "outside hitter",
    team_name: "Team C",
    country: "China",
    jersey_number: 45,
    experience_years: 13,
  },
  {
    player_id: 27,
    first_name: "Queenie",
    last_name: "Kirkpatrick",
    age: 37,
    height: 173.7,
    position: "outside hitter",
    team_name: "Team B",
    country: "Palestinian Territory",
    jersey_number: 88,
    experience_years: 9,
  },
  {
    player_id: 28,
    first_name: "Donna",
    last_name: "Giacopazzi",
    age: 22,
    height: 181.3,
    position: "middle blocker",
    team_name: "Team C",
    country: "Canada",
    jersey_number: 38,
    experience_years: 10,
  },
  {
    player_id: 29,
    first_name: "Selma",
    last_name: "Klesel",
    age: 21,
    height: 169.7,
    position: "libero",
    team_name: "Team C",
    country: "Poland",
    jersey_number: 64,
    experience_years: 8,
  },
  {
    player_id: 30,
    first_name: "Dick",
    last_name: "Wrennall",
    age: 33,
    height: 166.5,
    position: "setter",
    team_name: "Team C",
    country: "United States",
    jersey_number: 36,
    experience_years: 12,
  },
  {
    player_id: 31,
    first_name: "Aveline",
    last_name: "Costa",
    age: 25,
    height: 181.6,
    position: "opposite hitter",
    team_name: "Team A",
    country: "Bolivia",
    jersey_number: 4,
    experience_years: 0,
  },
  {
    player_id: 32,
    first_name: "Bradley",
    last_name: "Stokoe",
    age: 36,
    height: 175.5,
    position: "setter",
    team_name: "Team A",
    country: "Martinique",
    jersey_number: 96,
    experience_years: 18,
  },
  {
    player_id: 33,
    first_name: "Maxwell",
    last_name: "Sarll",
    age: 21,
    height: 155.1,
    position: "setter",
    team_name: "Team A",
    country: "Luxembourg",
    jersey_number: 97,
    experience_years: 9,
  },
  {
    player_id: 34,
    first_name: "Jule",
    last_name: "Houliston",
    age: 24,
    height: 162.4,
    position: "outside hitter",
    team_name: "Team A",
    country: "Indonesia",
    jersey_number: 72,
    experience_years: 7,
  },
  {
    player_id: 35,
    first_name: "Darin",
    last_name: "Norfolk",
    age: 27,
    height: 151.8,
    position: "middle blocker",
    team_name: "Team B",
    country: "China",
    jersey_number: 27,
    experience_years: 3,
  },
  {
    player_id: 36,
    first_name: "Cleavland",
    last_name: "Beadel",
    age: 19,
    height: 181.9,
    position: "middle blocker",
    team_name: "Team C",
    country: "Finland",
    jersey_number: 7,
    experience_years: 9,
  },
  {
    player_id: 37,
    first_name: "Pip",
    last_name: "Duckham",
    age: 26,
    height: 173.8,
    position: "opposite hitter",
    team_name: "Team B",
    country: "Russia",
    jersey_number: 47,
    experience_years: 19,
  },
  {
    player_id: 38,
    first_name: "Jimmie",
    last_name: "Inder",
    age: 28,
    height: 167.7,
    position: "setter",
    team_name: "Team B",
    country: "Czech Republic",
    jersey_number: 92,
    experience_years: 0,
  },
  {
    player_id: 39,
    first_name: "Bendick",
    last_name: "Hollibone",
    age: 27,
    height: 198.8,
    position: "libero",
    team_name: "Team A",
    country: "Indonesia",
    jersey_number: 58,
    experience_years: 19,
  },
  {
    player_id: 40,
    first_name: "Flo",
    last_name: "Mcall",
    age: 31,
    height: 190.5,
    position: "outside hitter",
    team_name: "Team A",
    country: "Mongolia",
    jersey_number: 65,
    experience_years: 9,
  },
  {
    player_id: 41,
    first_name: "Cindy",
    last_name: "Barbour",
    age: 31,
    height: 196.7,
    position: "middle blocker",
    team_name: "Team A",
    country: "Indonesia",
    jersey_number: 92,
    experience_years: 10,
  },
  {
    player_id: 42,
    first_name: "Hailee",
    last_name: "Martinie",
    age: 30,
    height: 169.7,
    position: "opposite hitter",
    team_name: "Team A",
    country: "Colombia",
    jersey_number: 69,
    experience_years: 12,
  },
  {
    player_id: 43,
    first_name: "Gal",
    last_name: "Khilkov",
    age: 27,
    height: 179.6,
    position: "opposite hitter",
    team_name: "Team C",
    country: "Sweden",
    jersey_number: 68,
    experience_years: 5,
  },
  {
    player_id: 44,
    first_name: "Waverley",
    last_name: "Beller",
    age: 31,
    height: 154.9,
    position: "opposite hitter",
    team_name: "Team A",
    country: "Comoros",
    jersey_number: 17,
    experience_years: 15,
  },
  {
    player_id: 45,
    first_name: "Juline",
    last_name: "Louw",
    age: 31,
    height: 167.6,
    position: "opposite hitter",
    team_name: "Team C",
    country: "Finland",
    jersey_number: 39,
    experience_years: 16,
  },
  {
    player_id: 46,
    first_name: "Dagmar",
    last_name: "Gloster",
    age: 24,
    height: 154.4,
    position: "libero",
    team_name: "Team B",
    country: "China",
    jersey_number: 6,
    experience_years: 16,
  },
  {
    player_id: 47,
    first_name: "Alister",
    last_name: "Czajka",
    age: 22,
    height: 185.4,
    position: "outside hitter",
    team_name: "Team C",
    country: "Palestinian Territory",
    jersey_number: 79,
    experience_years: 5,
  },
  {
    player_id: 48,
    first_name: "Elvin",
    last_name: "Ginglell",
    age: 22,
    height: 170.1,
    position: "libero",
    team_name: "Team A",
    country: "Peru",
    jersey_number: 57,
    experience_years: 6,
  },
  {
    player_id: 49,
    first_name: "Rollins",
    last_name: "Duferie",
    age: 38,
    height: 155.5,
    position: "setter",
    team_name: "Team B",
    country: "Japan",
    jersey_number: 66,
    experience_years: 10,
  },
  {
    player_id: 50,
    first_name: "Jacynth",
    last_name: "Bartelli",
    age: 35,
    height: 157.0,
    position: "libero",
    team_name: "Team B",
    country: "Ethiopia",
    jersey_number: 38,
    experience_years: 2,
  },
  {
    player_id: 51,
    first_name: "Faulkner",
    last_name: "Ragdale",
    age: 28,
    height: 156.9,
    position: "opposite hitter",
    team_name: "Team A",
    country: "Brazil",
    jersey_number: 78,
    experience_years: 17,
  },
  {
    player_id: 52,
    first_name: "Amy",
    last_name: "Arnoll",
    age: 19,
    height: 175.8,
    position: "libero",
    team_name: "Team A",
    country: "Poland",
    jersey_number: 19,
    experience_years: 10,
  },
  {
    player_id: 53,
    first_name: "Rochell",
    last_name: "Nanetti",
    age: 18,
    height: 188.7,
    position: "setter",
    team_name: "Team A",
    country: "Syria",
    jersey_number: 51,
    experience_years: 3,
  },
  {
    player_id: 54,
    first_name: "Jameson",
    last_name: "MattiCCI",
    age: 27,
    height: 185.1,
    position: "outside hitter",
    team_name: "Team A",
    country: "Ghana",
    jersey_number: 19,
    experience_years: 16,
  },
  {
    player_id: 55,
    first_name: "Marita",
    last_name: "Ancell",
    age: 22,
    height: 152.9,
    position: "opposite hitter",
    team_name: "Team B",
    country: "Sweden",
    jersey_number: 82,
    experience_years: 15,
  },
  {
    player_id: 56,
    first_name: "Ty",
    last_name: "Buffery",
    age: 38,
    height: 178.2,
    position: "libero",
    team_name: "Team A",
    country: "Venezuela",
    jersey_number: 16,
    experience_years: 15,
  },
  {
    player_id: 57,
    first_name: "Cecile",
    last_name: "Greim",
    age: 39,
    height: 150.3,
    position: "opposite hitter",
    team_name: "Team A",
    country: "Russia",
    jersey_number: 38,
    experience_years: 1,
  },
  {
    player_id: 58,
    first_name: "Carree",
    last_name: "Bolle",
    age: 26,
    height: 196.0,
    position: "libero",
    team_name: "Team B",
    country: "Brazil",
    jersey_number: 27,
    experience_years: 9,
  },
  {
    player_id: 59,
    first_name: "Derward",
    last_name: "Hanny",
    age: 39,
    height: 157.2,
    position: "setter",
    team_name: "Team C",
    country: "Indonesia",
    jersey_number: 45,
    experience_years: 12,
  },
  {
    player_id: 60,
    first_name: "Derril",
    last_name: "O'Duilleain",
    age: 29,
    height: 170.6,
    position: "setter",
    team_name: "Team B",
    country: "Indonesia",
    jersey_number: 85,
    experience_years: 4,
  },
  {
    player_id: 61,
    first_name: "Sharity",
    last_name: "Learmouth",
    age: 40,
    height: 162.6,
    position: "outside hitter",
    team_name: "Team C",
    country: "Canada",
    jersey_number: 78,
    experience_years: 19,
  },
  {
    player_id: 62,
    first_name: "Holly",
    last_name: "Ebbing",
    age: 38,
    height: 181.9,
    position: "opposite hitter",
    team_name: "Team C",
    country: "China",
    jersey_number: 97,
    experience_years: 8,
  },
  {
    player_id: 63,
    first_name: "Abram",
    last_name: "Skepper",
    age: 22,
    height: 172.5,
    position: "middle blocker",
    team_name: "Team A",
    country: "Colombia",
    jersey_number: 97,
    experience_years: 4,
  },
  {
    player_id: 64,
    first_name: "Boonie",
    last_name: "Hessing",
    age: 30,
    height: 194.2,
    position: "libero",
    team_name: "Team C",
    country: "Czech Republic",
    jersey_number: 79,
    experience_years: 15,
  },
  {
    player_id: 65,
    first_name: "Darell",
    last_name: "Merrison",
    age: 39,
    height: 176.3,
    position: "outside hitter",
    team_name: "Team B",
    country: "China",
    jersey_number: 36,
    experience_years: 0,
  },
  {
    player_id: 66,
    first_name: "Erminie",
    last_name: "Petruskevich",
    age: 36,
    height: 192.7,
    position: "middle blocker",
    team_name: "Team B",
    country: "Belarus",
    jersey_number: 49,
    experience_years: 3,
  },
  {
    player_id: 67,
    first_name: "Jennifer",
    last_name: "Sallery",
    age: 36,
    height: 163.1,
    position: "libero",
    team_name: "Team C",
    country: "Thailand",
    jersey_number: 74,
    experience_years: 18,
  },
  {
    player_id: 68,
    first_name: "Loydie",
    last_name: "Duchenne",
    age: 25,
    height: 159.1,
    position: "opposite hitter",
    team_name: "Team C",
    country: "France",
    jersey_number: 97,
    experience_years: 10,
  },
  {
    player_id: 69,
    first_name: "Tait",
    last_name: "Shemwell",
    age: 36,
    height: 194.8,
    position: "outside hitter",
    team_name: "Team B",
    country: "France",
    jersey_number: 3,
    experience_years: 11,
  },
  {
    player_id: 70,
    first_name: "Sanson",
    last_name: "Spohrmann",
    age: 34,
    height: 187.9,
    position: "setter",
    team_name: "Team C",
    country: "Portugal",
    jersey_number: 20,
    experience_years: 18,
  },
  {
    player_id: 71,
    first_name: "Constantino",
    last_name: "Raw",
    age: 22,
    height: 167.2,
    position: "outside hitter",
    team_name: "Team C",
    country: "Gambia",
    jersey_number: 14,
    experience_years: 3,
  },
  {
    player_id: 72,
    first_name: "Deirdre",
    last_name: "Ramsdell",
    age: 26,
    height: 178.7,
    position: "middle blocker",
    team_name: "Team A",
    country: "Finland",
    jersey_number: 14,
    experience_years: 13,
  },
  {
    player_id: 73,
    first_name: "Harrietta",
    last_name: "Luard",
    age: 35,
    height: 197.5,
    position: "setter",
    team_name: "Team C",
    country: "Japan",
    jersey_number: 19,
    experience_years: 8,
  },
  {
    player_id: 74,
    first_name: "Luise",
    last_name: "Triggel",
    age: 40,
    height: 155.8,
    position: "libero",
    team_name: "Team B",
    country: "Peru",
    jersey_number: 35,
    experience_years: 5,
  },
  {
    player_id: 75,
    first_name: "Rollo",
    last_name: "McCloughen",
    age: 26,
    height: 170.1,
    position: "opposite hitter",
    team_name: "Team C",
    country: "Ukraine",
    jersey_number: 26,
    experience_years: 18,
  },
  {
    player_id: 76,
    first_name: "Rainer",
    last_name: "Coumbe",
    age: 36,
    height: 178.9,
    position: "outside hitter",
    team_name: "Team C",
    country: "China",
    jersey_number: 85,
    experience_years: 14,
  },
  {
    player_id: 77,
    first_name: "Rik",
    last_name: "Kevlin",
    age: 32,
    height: 180.7,
    position: "middle blocker",
    team_name: "Team C",
    country: "China",
    jersey_number: 48,
    experience_years: 14,
  },
  {
    player_id: 78,
    first_name: "Ludovika",
    last_name: "Attridge",
    age: 24,
    height: 168.3,
    position: "libero",
    team_name: "Team A",
    country: "China",
    jersey_number: 47,
    experience_years: 15,
  },
  {
    player_id: 79,
    first_name: "Dorothea",
    last_name: "Swetland",
    age: 39,
    height: 180.3,
    position: "libero",
    team_name: "Team B",
    country: "Russia",
    jersey_number: 15,
    experience_years: 13,
  },
  {
    player_id: 80,
    first_name: "Trix",
    last_name: "Cheshire",
    age: 31,
    height: 194.6,
    position: "opposite hitter",
    team_name: "Team A",
    country: "Brazil",
    jersey_number: 34,
    experience_years: 10,
  },
  {
    player_id: 81,
    first_name: "Sybille",
    last_name: "Lube",
    age: 25,
    height: 154.5,
    position: "libero",
    team_name: "Team B",
    country: "China",
    jersey_number: 65,
    experience_years: 14,
  },
  {
    player_id: 82,
    first_name: "Evelyn",
    last_name: "Mapletoft",
    age: 30,
    height: 198.7,
    position: "opposite hitter",
    team_name: "Team A",
    country: "China",
    jersey_number: 65,
    experience_years: 13,
  },
  {
    player_id: 83,
    first_name: "Ellynn",
    last_name: "Grassin",
    age: 18,
    height: 153.2,
    position: "libero",
    team_name: "Team C",
    country: "Nicaragua",
    jersey_number: 78,
    experience_years: 15,
  },
  {
    player_id: 84,
    first_name: "Bartholomeus",
    last_name: "Hains",
    age: 19,
    height: 183.5,
    position: "middle blocker",
    team_name: "Team B",
    country: "Palestinian Territory",
    jersey_number: 99,
    experience_years: 14,
  },
  {
    player_id: 85,
    first_name: "Alida",
    last_name: "Simonutti",
    age: 36,
    height: 176.5,
    position: "libero",
    team_name: "Team C",
    country: "Poland",
    jersey_number: 83,
    experience_years: 11,
  },
  {
    player_id: 86,
    first_name: "Darb",
    last_name: "McIlhagga",
    age: 37,
    height: 187.1,
    position: "outside hitter",
    team_name: "Team B",
    country: "China",
    jersey_number: 61,
    experience_years: 1,
  },
  {
    player_id: 87,
    first_name: "Iona",
    last_name: "Deignan",
    age: 24,
    height: 155.7,
    position: "opposite hitter",
    team_name: "Team B",
    country: "Sweden",
    jersey_number: 5,
    experience_years: 16,
  },
  {
    player_id: 88,
    first_name: "Meryl",
    last_name: "Seater",
    age: 39,
    height: 188.8,
    position: "middle blocker",
    team_name: "Team C",
    country: "Palestinian Territory",
    jersey_number: 46,
    experience_years: 5,
  },
  {
    player_id: 89,
    first_name: "Martynne",
    last_name: "Wyman",
    age: 19,
    height: 152.2,
    position: "setter",
    team_name: "Team B",
    country: "New Zealand",
    jersey_number: 68,
    experience_years: 6,
  },
  {
    player_id: 90,
    first_name: "Jobyna",
    last_name: "Mattheeuw",
    age: 23,
    height: 166.5,
    position: "setter",
    team_name: "Team B",
    country: "Argentina",
    jersey_number: 41,
    experience_years: 10,
  },
  {
    player_id: 91,
    first_name: "Diana",
    last_name: "Denziloe",
    age: 36,
    height: 195.6,
    position: "outside hitter",
    team_name: "Team B",
    country: "Switzerland",
    jersey_number: 68,
    experience_years: 4,
  },
  {
    player_id: 92,
    first_name: "Rock",
    last_name: "Roselli",
    age: 38,
    height: 196.7,
    position: "setter",
    team_name: "Team C",
    country: "Indonesia",
    jersey_number: 35,
    experience_years: 6,
  },
  {
    player_id: 93,
    first_name: "Rance",
    last_name: "Cloonan",
    age: 24,
    height: 172.7,
    position: "libero",
    team_name: "Team C",
    country: "Philippines",
    jersey_number: 32,
    experience_years: 8,
  },
  {
    player_id: 94,
    first_name: "Esra",
    last_name: "Webland",
    age: 40,
    height: 161.4,
    position: "outside hitter",
    team_name: "Team A",
    country: "Tanzania",
    jersey_number: 62,
    experience_years: 2,
  },
  {
    player_id: 95,
    first_name: "Tana",
    last_name: "Lemmen",
    age: 20,
    height: 158.1,
    position: "libero",
    team_name: "Team A",
    country: "France",
    jersey_number: 96,
    experience_years: 12,
  },
  {
    player_id: 96,
    first_name: "Shellysheldon",
    last_name: "Jellyman",
    age: 37,
    height: 172.5,
    position: "outside hitter",
    team_name: "Team C",
    country: "China",
    jersey_number: 84,
    experience_years: 7,
  },
  {
    player_id: 97,
    first_name: "Jacklyn",
    last_name: "Ladloe",
    age: 28,
    height: 190.9,
    position: "middle blocker",
    team_name: "Team B",
    country: "Bolivia",
    jersey_number: 9,
    experience_years: 20,
  },
  {
    player_id: 98,
    first_name: "Sheffy",
    last_name: "Krolman",
    age: 28,
    height: 193.4,
    position: "opposite hitter",
    team_name: "Team C",
    country: "China",
    jersey_number: 98,
    experience_years: 15,
  },
  {
    player_id: 99,
    first_name: "Gerhardine",
    last_name: "Ellingsworth",
    age: 36,
    height: 167.9,
    position: "outside hitter",
    team_name: "Team A",
    country: "Brazil",
    jersey_number: 78,
    experience_years: 11,
  },
  {
    player_id: 100,
    first_name: "Brendin",
    last_name: "Moodie",
    age: 28,
    height: 180.6,
    position: "opposite hitter",
    team_name: "Team A",
    country: "Russia",
    jersey_number: 72,
    experience_years: 8,
  },
];
