import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  LoginLink,
  LogoutLink,
  RegisterLink,
} from "@kinde-oss/kinde-auth-nextjs/components";
import { Button } from "@/components/ui/button";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Test app",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { isAuthenticated, getUser } = getKindeServerSession();
  const user = await getUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex justify-between items-center p-8 px-24">
          <h1 className="font-bold text-2xl">AppName</h1>
          {(await isAuthenticated()) ? (
            <div className="flex gap-3 items-center">
              <Avatar className="w-12 h-12">
                <AvatarImage src={user?.picture || ""} alt="@shadcn" />
                <AvatarFallback>
                  {user?.given_name![0]} {user?.family_name![0]}
                </AvatarFallback>
              </Avatar>
              <div>
                <p className="font-medium -mb-1">
                  {user?.given_name} {user?.family_name}
                </p>
                <LogoutLink className="font-medium text-sm text-slate-600">
                  Sign out
                </LogoutLink>
              </div>
            </div>
          ) : (
            <div className="flex gap-2">
              <LoginLink>
                <Button variant={"secondary"}>Login</Button>
              </LoginLink>
              <RegisterLink>
                <Button>Register</Button>
              </RegisterLink>
            </div>
          )}
        </nav>
        {children}
      </body>
    </html>
  );
}
